services:
  backend:
    image: cherhrab
    networks:
      - net
    ports:
      - "8088:8080"
    environment:
      VIRTUAL_HOST: "ch.pulpudev.com" 
      LETSENCRYPT_HOST: "ch.pulpudev.com" 

networks:
  net:
    external: true
