services:
  webserver:
    image: httpd:alpine3.22
    networks:
      - net
    environment:
      VIRTUAL_HOST: "ch.pulpudev.com" 
      LETSENCRYPT_HOST: "ch.pulpudev.com" 
    volumes:
      - ./index.html:/usr/local/apache2/htdocs/

networks:
  net:
    external: true
