services:
  webserver:
    image: httpd:alpine3.22
    networks:
      - net
    ports:
      - "8080:80"
    environment:
      VIRTUAL_HOST: "ch.pulpudev.com" 
      LETSENCRYPT_HOST: "ch.pulpudev.com" 
    volumes:
      - ./html/:/usr/local/apache2/htdocs/

networks:
  net:
    external: true
